apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-sip-catalog
  namespace: sip
spec:
  displayName: IBM SIP Operator Catalog
  # For the image name, see the following catalog source image names table and use the appropriate value.
  image: cp.icr.io/cpopen/ibm-oms-sip-operator-catalog:v1.0 
  publisher: IBM
  sourceType: grpc 
  updateStrategy:
    registryPoll:
      interval: 10m0s
